version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - .:/app
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A GallerySearch worker --loglevel=info

volumes:
  media:
