# Generated by Django 4.2.21 on 2025-05-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='embedding',
            field=models.BinaryField(blank=True),
        ),
    ]
