# Generated by Django 4.2.21 on 2025-05-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
