# Generated by Django 4.2.21 on 2025-06-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_image_description_alter_image_embedding'),
        ('gallery', '0003_remove_image_path_alter_image_image_file_and_more'),
    ]

    operations = [
    ]
