# Generated by Django 4.2.21 on 2025-06-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_image_path_alter_image_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='similarity',
        ),
    ]
